name: gemastik
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision
  - pillow
  - requests
  - setuptools
  - google-api-python-client
  - google-auth-oauthlib
  - protobuf
  - pylint
  - black
  - black-jupyter
  - matplotlib
  - numpy
  - pandas
  - ipykernel
  - gdown
  - pip
  - pip:
      - -r requirements.txt
